# Generated by Django 5.2 on 2025-05-06 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории фразы', max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория фразы',
                'verbose_name_plural': 'Категории фраз',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Введите текст фразы', max_length=50, verbose_name='Текст фразы')),
                ('category', models.ForeignKey(help_text='Выберите категорию фразы', on_delete=django.db.models.deletion.CASCADE, to='phrasebook.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Фраза',
                'verbose_name_plural': 'Фразы',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Введите текст перевода фразы', max_length=50, verbose_name='Текст перевода')),
                ('audio', models.CharField(help_text='Введите ссылку на аудио перевода фразы', max_length=1000, verbose_name='Аудио перевода')),
                ('phrase', models.ForeignKey(help_text='Выберите фразу для перевода', on_delete=django.db.models.deletion.CASCADE, to='phrasebook.phrase', verbose_name='Фраза')),
            ],
            options={
                'verbose_name': 'Перевод фразы',
                'verbose_name_plural': 'Переводы фраз',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LearnedPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('translation', models.ForeignKey(help_text='Выберите фразу, которую хотите добавить в выученное', on_delete=django.db.models.deletion.CASCADE, to='phrasebook.translation', verbose_name='Фраза')),
            ],
            options={
                'verbose_name': 'Выученная фраза',
                'verbose_name_plural': 'Выученные фразы',
                'ordering': ['-id'],
                'unique_together': {('user', 'translation')},
            },
        ),
        migrations.CreateModel(
            name='FavoritePhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('translation', models.ForeignKey(help_text='Выберите фразу, которую хотите добавить в избранное', on_delete=django.db.models.deletion.CASCADE, to='phrasebook.translation', verbose_name='Фраза')),
            ],
            options={
                'verbose_name': 'Избранная фраза',
                'verbose_name_plural': 'Избранные фразы',
                'ordering': ['-id'],
                'unique_together': {('user', 'translation')},
            },
        ),
    ]
