# Generated by Django 5.2 on 2025-05-06 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории слов', max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория слов',
                'verbose_name_plural': 'Категории слов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='Введите название языка происхождения', max_length=50, verbose_name='Язык происхождения')),
            ],
            options={
                'verbose_name': 'Язык происхождения',
                'verbose_name_plural': 'Языки происхождения',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название части речи слова', max_length=50, verbose_name='Название части речи')),
            ],
            options={
                'verbose_name': 'Часть речи',
                'verbose_name_plural': 'Части речи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Введите текст слова', max_length=50, verbose_name='Текст слова')),
                ('category', models.ForeignKey(help_text='Выберите категорию слова', on_delete=django.db.models.deletion.CASCADE, to='dictionary.category', verbose_name='Категория')),
                ('part_of_speech', models.ForeignKey(help_text='Выберите часть речи слова', on_delete=django.db.models.deletion.CASCADE, to='dictionary.partofspeech', verbose_name='Часть речи')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Введите текст перевода слова', max_length=50, verbose_name='Текст перевода')),
                ('audio', models.CharField(help_text='Введите ссылку на аудио перевода слова', max_length=1000, verbose_name='Аудио перевода')),
                ('origin', models.ForeignKey(help_text='Выберите язык происхождения перевода', on_delete=django.db.models.deletion.CASCADE, to='dictionary.origin', verbose_name='Язык происхождения')),
                ('word', models.ForeignKey(help_text='Выберите слово для перевода', on_delete=django.db.models.deletion.CASCADE, to='dictionary.word', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Перевод слова',
                'verbose_name_plural': 'Переводы слова',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LearnedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('translation', models.ForeignKey(help_text='Выберите слово, которое хотите добавить в выученное', on_delete=django.db.models.deletion.CASCADE, to='dictionary.translation', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Выученное слово',
                'verbose_name_plural': 'Выученные слова',
                'ordering': ['-id'],
                'unique_together': {('user', 'translation')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('translation', models.ForeignKey(help_text='Выберите слово, которое хотите добавить в избранное', on_delete=django.db.models.deletion.CASCADE, to='dictionary.translation', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Избранное слово',
                'verbose_name_plural': 'Избранные слова',
                'ordering': ['-id'],
                'unique_together': {('user', 'translation')},
            },
        ),
    ]
