# Generated by Django 5.2 on 2025-05-06 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории источника', max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория источника',
                'verbose_name_plural': 'Категории источников',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Введите название источника', max_length=255, verbose_name='Название источника')),
                ('link', models.CharField(help_text='Введите ссылку на источник', max_length=1000, verbose_name='Текст ссылки на источник')),
                ('category', models.ForeignKey(help_text='Выберите категорию источника', on_delete=django.db.models.deletion.CASCADE, to='sources.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='MarkedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('source', models.ForeignKey(help_text='Выберите источник', on_delete=django.db.models.deletion.CASCADE, to='sources.source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Отмеченный источник',
                'verbose_name_plural': 'Отмеченные источники',
                'ordering': ['-id'],
                'unique_together': {('user', 'source')},
            },
        ),
    ]
