# Generated by Django 5.2 on 2025-05-06 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(help_text='Введите букву алфавита', max_length=10, verbose_name='Буква')),
                ('audio', models.CharField(help_text='Введите ссылку на аудио буквы', max_length=1000, verbose_name='Аудио буквы')),
            ],
            options={
                'verbose_name': 'Буква',
                'verbose_name_plural': 'Буквы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LearnedLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('letter', models.ForeignKey(help_text='Выберите букву', on_delete=django.db.models.deletion.CASCADE, to='alphabet.letter', verbose_name='Буква')),
            ],
            options={
                'verbose_name': 'Прогресс изучения алфавита',
                'verbose_name_plural': 'Прогресс изучения алфавита',
                'ordering': ['-id'],
                'unique_together': {('user', 'letter')},
            },
        ),
    ]
